### ISSUE TITLE
AuthCheck is defined as ReactNode rather than JSX.Element

### ISSUE THREAD

**Issue by waixwong** [FirebaseExtended/reactfire#138]
AuthCheck is defined as ReactNode rather than JSX.Element in index.d.ts

This produces the following TS error when adding AuthCheck:
TS2605: JSX element type 'ReactNode' is not a constructor function for JSX elements.

### Version info
**React:**
16.8.6

**Firebase:**
5.10.0

**ReactFire:**
2.0.0

**Other (e.g. Node, browser, operating system) (if applicable):**
10.16

### Steps to reproduce
https://stackblitz.com/edit/react-ts-k6abtn
line 56

**Comment by jhuleatt** [comment]
I originally picked `ReactNode` because that is what the [core React typings use for components like Suspense](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/752847f11e21276a22ef5703294bc689a0f3445a/types/react/index.d.ts#L347). 

It doesn't look like the typings for React use `JSX.Element` at all, so I'm a little worried about switching to that. I think this type error is more due to a [TypeScript bug](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544), but I'll give `JSX.Element` a shot and see if that clears up the warnings. Thanks for filing this!

**Comment by pearlyplan** [comment]
Hi - is there any update on this?  Happy to do a PR with the new typing.

**Comment by seanemmer** [comment]
Hi, is there any update on this?  Happy to do a PR with the new typing.

**Comment by pmithunish** [comment]
Adding the following snippet helped me get rid of the `ts(2605)` error when using `AuthCheck`.
```ts
declare module "reactfire/auth" {
  function AuthCheck({
    auth,
    fallback,
    children,
    requiredClaims
  }: AuthCheckProps): JSX.Element;
}
```
Hope it helps! 😃

**Comment by jhuleatt** [comment]
Sounds like the consensus is that `JSX.Element` is the way to go! @seanemmer if you have the time, a PR would be a big help! I think `<SuspenseWithPerf>` will need the same type updates.
