### ISSUE TITLE
useUser initial value null within AuthCheck children 

### ISSUE THREAD

**Issue by cdock1029** [FirebaseExtended/reactfire#155]
### Version info

**React:** 16.10.2

**Firebase:** 7.2.9

**ReactFire:** 2.0.0-alpha.2

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

https://codesandbox.io/s/competent-mendeleev-svfjb

### Steps to reproduce

Use `AuthCheck` with fallback login page.
Login in.
In "authorized" child component, call `useUser`
Access properties of `user` without checking for null.

### Expected behavior

Since `AuthCheck` children won't render until user is logged in (not null), I'd expect all rendered descendant components under `AuthCheck` to have access to a not null user.

### Actual behavior
Because of how `useUser` instantiates a new observable for every separate usage, there will always be an initial null value. Ideally, we wouldn't have to check for this everywhere in a component tree rendered after `AuthCheck` has a user.

I don't see the use case for having an optional `startWith` parameter in `useUser` instead of defaulting to `app.auth().currentUser` and not have to pass in ourselves everywhere.

https://github.com/FirebaseExtended/reactfire/blob/99dac6c4cacef2b6fc59b53de340b935363a1e06/reactfire/auth/index.tsx#L41

**Comment by cdock1029** [comment]
Great! Sounds like we're on the same page. Just to complete my thought for clarity.. again not sure what startWithValue is useful for, but certainly can keep it / make simple fix with something like this probably?

```js
options ? options.startWithValue : auth.currentUser
```

**Comment by jhuleatt** [comment]
It turns out this was caused by a bug deeper in the plumbing of ReactFire. When a hook makes the same request as one before it (in this case, the `useUser` in `AuthCheck` and then the `useUser` in your component), the hook was receiving the first value the hook before it received, instead of its most recent value. So I've fixed that, and all of reactfire will benefit!

Always using `auth.currentUser` as the startWithValue does make a lot of sense! Since it turns out it wasn't needed for the bugfix and is more of a behavior change, I've created #158 to track that work.

Side note: _What `startWithValue` does: If you provide it, the ReactFire hooks won't throw a Promise, and will instead immediately return whatever value you provided. [Docs](https://github.com/FirebaseExtended/reactfire/blob/master/docs/reference.md#useuser)_
