### ISSUE TITLE
Attempted import error: 'useFirestoreCollectionData' is not exported from 'reactfire'

### ISSUE THREAD

**Issue by MuratDoner** [FirebaseExtended/reactfire#157]
Hello.
 I tried sample-simple (reactfire) on my local. I get this error: `"Attempted import error: 'useFirestoreCollectionData' is not exported from 'reactfire'."`
I am sure, it is something about the version of reactfire. 
What is the best way to get over it?

**Comment by jhuleatt** [comment]
Hi @MuratDoner, sounds like yarn is pulling in the published version of ReactFire (which doesn't include `useFirestoreCollectionData` yet) instead of getting it from your local machine. Did you remember to run the build (`yarn watch` in the [instructions here](https://github.com/FirebaseExtended/reactfire#for-development)) before doing an install in the `sample-simple` directory?

If you want to avoid the building stuff, a quick workaround is to just change the dependency in sample-simple's `package.json` to the latest canary, [`2.0.0-canary.99dac6c`](https://www.npmjs.com/package/reactfire?activeTab=versions)

**Comment by MuratDoner** [comment]
Hi Jeff,
 Now, it is working like a charm! Thanks :)
 It was my fault; I did not pay enough attention to the documentation.
 Best Regards.

**Comment by jhuleatt** [comment]
Glad it is working 😃
