### ISSUE TITLE
Query: Join in Firestore

### ISSUE THREAD

**Issue by catrawalkar** [FirebaseExtended/reactfire#183]
### Version info

**React:** 16.9.0

**Firebase:** 7.2.0

**ReactFire:** 2.0.0-canary.d96bda4

### Query

Consider following database structure: 

 - Orders Collection
	 - Order Document (Order1)
		 - `price: $100`
		 - `quantity: 10`
		 - `item: Item1` (This is  of type Reference)
		 - `user: User1` (This is  of type Reference)
 -  Items Collection
	 - Item Document (Item1)
		 - `item name: pencil`
		 - `rate: $10`
 - Users Collection
	 - User Document (User1)
		 - `name: Chinmay`
		 - `email id: chinmay@example.com`
		 - `mobile no: +918765421421`

What is the correct way to query Order1 document from Orders Collection ? My expected result is:
```
{
	price: $100,
	quantity: 10,
	item: {
		item name: pencil,
		rate: $10
	},
	user:{
		name: Chinmay,
		email id: chinmay@example.com,
		mobile no: +918765421421
	}
}
```

Am I going in right direction? Or shall I model this using `Subcollections` in firestore?

I know I can use `Query inside Query` in following way:

```
const  firebaseApp = useFirebaseApp();
const  ordersReference = firebaseApp.firestore()
			.collection("orders").doc(orderId);

const  ordersDoc = useFirestoreDoc(ordersReference);

const  order = ordersDoc.data();

const  itemsReference = firebaseApp.firestore()
			.collection("items").doc(order.item);

const  itemsDoc = useFirestoreDoc(itemsReference);

const  item = itemsDoc.data();

const  usersReference = firebaseApp.firestore()
			.collection("users").doc(order.user);

const  usersDoc = useFirestoreDoc(usersReference );

const  user = usersDoc.data();

order.item = item;
order.user = user;
```

Above code makes 3 round trips in all, 1 for order 1 for item and 1 for user. Is this the correct way?

If I should go for `subcollections` what good is the datatype `Reference` in firestore for?

If I should still for `subcollections` can you please help me with the datamodel I should design?

**Comment by mbleigh** [comment]
Cloud Firestore is a non-relational database, there are no JOINs. Typically
you would want to model your data to match how you query it, and
denormalize as necessary.

**Comment by jhuleatt** [comment]
+1 to @mbleigh's answer. There are a number of similar questions about Firestore data modeling on StackOverflow, so taking a look there may help. Here's a [relevant answer](https://stackoverflow.com/a/56666799/4816918), and [here is the full list of `join` questions](https://stackoverflow.com/search?tab=votes&q=%5bgoogle-cloud-firestore%5d%20join). If after that you're still looking for Firestore data modeling help, please ask in the #firestore channel on the [firebase.community](https://firebase.community/) Slack.

In terms of ReactFire, doing 3 `useFirestoreDoc` calls in the same component will work, it probably just isn't ideal since you'll have to wait for 3 sequential network calls to complete.
