### ISSUE TITLE
Property 'GoogleAuthProvider' does not exist on type 'Auth'

### ISSUE THREAD

**Issue by seanaguinaga** [FirebaseExtended/reactfire#223]
Recently updated packages and this happened when trying to combine https://github.com/firebase/firebaseui-web-react with reactfire

<img width="485" alt="Annotation 2020-03-09 085614" src="https://user-images.githubusercontent.com/15254340/76232392-dd825c80-61e3-11ea-9345-b5e7575c9895.png">

Was there a change on how this works? According to the firebase docs GoogleAuthProvider should still be a part of Auth.  https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider

**Comment by jhuleatt** [comment]
@seanaguinaga good question! This is a recent change we're still working on documenting. Changing the line

```js
const auth = useAuth();
```

to this (don't call `useAuth` as a function):

```js
const auth = useAuth;
```

Should fix things. You can see an example in the sample code:

https://github.com/FirebaseExtended/reactfire/blob/5487096955aa411fb2cac6b17513d09143aadb90/sample/src/Auth.js#L28-L39

This change was implemented in #215 . We switched the API because we realized that in a lot of places we needed to double call the ReactFire observables `useAuth()()`, `useFirestore()()`, which felt weird.

**Comment by seanaguinaga** [comment]
Got it got it! Thank you!
