### ISSUE TITLE
Can't use firebase.firestore.FieldValue.serverTimestamp() in a separate function

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#227]
repro (click the button to see the error): https://stackblitz.com/fork/react-cmc6zd

calling `firebase.firestore.FieldValue....` in a function that isn't a function component causes a "you broke the rules of hooks" error.

**Comment by wizawuza** [comment]
It's like this for any hook, this isn't specific to reactfire.

You'd have to do one of two things.
`const firestore = useFirestore();` <= notice the ()
That won't work because you want FieldValue.. the above works for stuff like firestore.collection('collectionName')....
You can also try:
`const fieldValue = useFirestore.FieldValue;`
and later in your code do `time: fieldValue.serverTimestamp()`

**Comment by mironovich** [comment]
got here because after
`const firestore = useFirestore()`

`firestore.FieldValue` was undefined

This helped, thanks
`const fieldValue = useFirestore.FieldValue;`
