### ISSUE TITLE
Reactfire and FirebaseUI when Firebase is hosted by CDN

### ISSUE THREAD

**Issue by Carduelis** [FirebaseExtended/reactfire#273]
Hello!

I'm struggling with reactfire v2 and using FirebaseUI with Firebase loded by CDN.

Unfortunately, reactfire requires firebase to be installed and added to `package.json`, therefore it will increase the bundle size of app.

Unfortunately, reactfire **doesn't work without** `npm i firebase`. I think, usage firebase hosted on `/__/` folder and loading it using `defer` key -- is the best way to include it to the app.

Is there a way to use `reactfire` with Firebase added by cdn `<script defer />` links?

Btw, What is the best practice for usage `reactfire` with `firebaseui`? If I use `reactfire` and `firebaseui` it [throws such error](https://github.com/firebase/firebaseui-web/issues/536) by attempting to sign up.
Put everything to `npm` and then bundle it up using code-splitting? (I use nextjs, it goes out of the box)

**Comment by jhuleatt** [comment]
Hey @Carduelis, the [sample](https://github.com/FirebaseExtended/reactfire/blob/0cdfc7d2e2179532d5caeae5d5ae705274c073bc/example/withoutSuspense/Auth.tsx#L45-L62) shows how to use ReactFire and FirebaseUI together.

Supporting the CDN builds of Firebase isn't something we target right now, but I think @jamesdaniels may be looking in to this?

**Comment by jamesdaniels** [comment]
While we do expect that the SDKs are coming in from a bundler we are dynamically importing them, so they won't affect your main bundle size. Webpack, et al. should code-split for you. When combined with SSR / pretense ring this will give your users a much better experience than simply a deferred script. 

Allowing CDN loading isn't a priority for us at the moment, due to bundlers giving you more flexibility and reducing the maintenance burden on us. 

Further, in the coming months we will be testing a new tree-shakable version of the Firebase JS SDK. Meaning your bundled version of the SDKs could be much smaller than those on the CDN, providing of course you don't use every single feature in the SDK.

That said, we are aiming to dynamically import the init.json.
